name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json

      - name: Set Firebase project
        run: firebase use bl-cursos --alias default

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
